import scrapy
import difflib

class BudgetSpider(scrapy.Spider):

    name = 'budget_data'

    custom_settings = {
        "DOWNLOAD_DELAY": 3,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 3,
        "HTTPCACHE_ENABLED": True
    }
    # Page it begins scraping
    start_urls = ['http://www.the-numbers.com/movie/budgets/all']
    
    def parse(self, response):
        for i in range(1,5402,100):         
            url = 'http://www.the-numbers.com/movie/budgets/all/'
            yield scrapy.Request(
                url = 'http://www.the-numbers.com/movie/budgets/all/' + str(i),  #url for each new movie page
                callback = self.parse_movie_list,       #calls method below to extract data from each movie pg
                meta={'url': url}
                )
 
       
    def parse_movie_list(self, response):
        # searches if each movie on the page is in missing list, if it is then it copies the details
        #once it finishes a page it goes back to method parse
        url = response.request.meta['url']
        Movies_pg_list = response.xpath('//table/tr/td/b/a/text()').extract() 
        print(Movies_pg_list)
        Miss_list = ['Transporter 3',
                     'Transporter 2',
                     'The Trip (2011)',
                     'The Trip to Italy',
                     'The Twilight Saga: Breaking Dawn Part 1',
                     'The Twilight Saga: Breaking Dawn Part 2',
                     '300: Rise of An Empire',
                     'Ernest Rides Again',
                     'Earth (2009)',
                     'Cinderella (2015)',
                     'Transformers: The Movie',
                     'Dhoom 2',
                     'Dhoom 3',
                     'Die Hard: With A Vengeance',
                     'Die Hard 2: Die Harder',
                     'The Dead Pool',
                     'Sudden Impact',
                     'Oz The Great and Powerful',
                     'The Jungle Book (2016)',
                     'Underworld: Blood Wars',
                     'Beauty and the Beast (2017)',
                     'Universal Soldier: Day of Reckoning',
                     'Dumb and Dumber',
                     'V/H/S: Viral',
                     'Vegas Vacation',
                     'Ernest Scared Stupid',
                     'Ernest Goes to Camp',
                     'Ernest Goes to Jail',
                     'Ernest Saves Christmas',
                     'Underworld: Rise of the Lycans',
                     'Underworld Awakening',
                     'Universal Soldier: The Return',
                     'Universal Soldier',
                     'V/H/S',
                     'The Woman in Black 2: Angel of Death',
                     'European Vacation',
                     "National Lampoon's Vacation",
                     'Christmas Vacation',
                     'The Work and the Glory III: A House Divided',
                     "Piglet's Big Movie",
                     'X2: X-Men United',
                     'The Work and the Glory II: American Zion',
                     'xXx: The Return of Xander Cage',
                     'XXX',
                     'Alice in Wonderland (2010)',
                     'Toy Story / Toy Story 2 (3D)',
                     'Return of the Texas Chainsaw Massacre',
                     'Step Up All In',
                     'Attack of the Clones: The IMAX Experience (IMAX)',
                     'The SpongeBob SquarePants Movie',
                     'Spy Kids 3D: Game Over',
                     'Return of the Jedi (Re-issue)',
                     'The Empire Strikes Back (Re-issue)',
                     'Star Wars (Re-issue)',
                     'Star Wars: Episode I - The Phantom Menace (in 3D)',
                     'Return of the Jedi (Special Edition)',
                     'The Empire Strikes Back (Special Edition)',
                     'Star Wars (Special Edition)',
                     'The Empire Strikes Back',
                     'Return of the Jedi',
                     'Star Wars: Episode II - Attack of the Clones',
                     'Star Wars',
                     'Star Wars: Episode III - Revenge of the Sith',
                     'Star Wars: Episode I - The Phantom Menace',
                     'Star Wars: The Force Awakens',
                     'Step Up 3-D',
                     'Teenage Mutant Ninja Turtles II',
                     'Teenage Mutant Ninja Turtles (2014)',
                     'Texas Chainsaw Massacre: The Next Generation',
                     'Leatherface: The Texas Chainsaw Massacre III',
                     "The Huntsman: Winter's War",
                     'The Smurfs and the Magic Flute',
                     'Smokey & the Bandit Part III',
                     "Frank Miller's Sin City: A Dame to Kill For",
                     'Shiloh 2: Shiloh Season',
                     'Scary Movie 5',
                     'The Santa Clause 3: The Escape Clause',
                     'Shiloh',
                     'Rocky III (Re-issue)',
                     'Robocop 3',
                     'Red 2',
                     'The Raid 2',
                     'Psycho III',
                     'Turbo: A Power Rangers Movie',
                     "Mighty Morphin' Power Rangers",
                     'Power Rangers (2017)',
                     'Psycho (1998)',
                     'Psycho II',
                     'The Raid: Redemption',
                     'Return of the Living Dead III',
                     'Return of the Living Dead 2',
                     'Return of the Living Dead',
                     'Robocop 2',
                     'Robocop',
                     'RoboCop (2014)',
                     'Rocky V',
                     'Rocky III',
                     'Rocky IV',
                     'Rugrats in Paris: The Movie',
                     'Aliens Vs. Predator - Requiem',
                     'Alien Resurrection',
                     'Alien Vs. Predator',
                     "Porky's (Re-issue)",
                     'Pokemon Heroes',
                     'Son of the Pink Panther',
                     'Ong Bak 3',
                     'Damien: The Omen Part II',
                     'The Omen (2006)',
                     'Ong Bak 2: The Beginning',
                     'Ong Bak: The Thai Warrior',
                     'Curse of the Pink Panther',
                     'Trail of the Pink Panther',
                     'The Pink Panther 2',
                     'The Pink Panther (2006)',
                     "Pirates of the Caribbean: At World's End",
                     "Pirates of the Caribbean: Dead Man's Chest",
                     'Planet of the Apes (2001)',
                     'Pokemon 4Ever',
                     'The Chipmunk Adventure',
                     'Pokemon: The Movie 2000',
                     'Police Academy 6: City Under Siege',
                     'Police Academy 5: Assignment:',
                     'American Ninja 4: The Annihilation',
                     'Police Academy 4: Citizens on Patrol',
                     'Police Academy 3: Back in Training',
                     'Police Academy 2: Their First Assignment',
                     'Poltergeist II: The Other Side',
                     'Amityville 3-D',
                     'Poltergeist (2015)',
                     "Porky's Revenge (Part III)",
                     'Batman: Mask of the Phantasm',
                     'Arthur 2: On the Rocks',
                     "Porky's II: The Next Day",
                     'American Ninja 3: Blood Hunt',
                     'American Ninja 2',
                     'American Ninja',
                     'Amityville II: The Possession',
                     'The Amityville Horror (2005)',
                     'Arthur (2011)',
                     'The Naked Gun 33 1/3: The Final Insult',
                     'Muppets from Space',
                     'Braddock: Missing in Action III',
                     'Missing in Action II: The Beginning',
                     "The Girl Who Kicked the Hornet's Nest",
                     'D3: The Mighty Ducks',
                     'D2: The Mighty Ducks',
                     'The Girl Who Played with Fire',
                     'Missing in Action',
                     'Mission: Impossible - Rogue Nation',
                     'Mission: Impossible - Ghost Protocol',
                     'Mission: Impossible II',
                     'The Muppets Take Manhattan',
                     'Muppet Treasure Island',
                     'The Naked Gun: From the Files of Police Squad!',
                     'The Naked Gun 2 1/2: The Smell of Fear',
                     'The Neverending Story II',
                     'The Neverending Story',
                     'A Nightmare on Elm Street 5: The Dream Child',
                     "A Nightmare on Elm Street 2: Freddy's Revenge",
                     "Freddy's Dead: The Final Nightmare",
                     'A Nightmare on Elm Street 3: Dream Warriors',
                     'A Nightmare on Elm Street (2010)',
                     'Freddy Vs. Jason',
                     'Oh, God! You Devil!',
                     'Oh, God!',
                     'Atlas Shrugged Part III: Who Is John Galt?',
                     'MIB 3',
                     'Major League: Back to the Minors',
                     "Tyler Perry's Diary of a Mad Black Woman",
                     'The Lord of the Rings (1978)',
                     "Look Who's Talking Now",
                     'The LEGO Movie',
                     'Lethal Weapon 2',
                     "Look Who's Talking Too",
                     "Look Who's Talking",
                     'The Road Warrior',
                     "Tyler Perry's Madea's Big Happy Family",
                     "Tyler Perry's Madea's Family Reunion",
                     'Boo! A Madea Halloween',
                     "Tyler Perry's Madea Goes to Jail",
                     'Major League II',
                     'Guardians of the Galaxy Vol. 2',
                     'Avatar: Special Edition',
                     'Meatballs II',
                     'Mechanic: Resurrection',
                     'Men in Black II',
                     'Batman and Robin',
                     'The LEGO Batman Movie',
                     'Benji Off the Leash',
                     'Benji the Hunted',
                     'Atlas Shrugged: Part I',
                     "Marvel's The Avengers",
                     'Bad News Bears',
                     'The Next Karate Kid',
                     'Jaws 2 (1980 re-issue)',
                     'Harry Potter IMAX Marathon',
                     'Fantastic Beasts and Where To Find Them',
                     'Harry Potter and the Deathly Hallows Part 1',
                     "Harry Potter and the Sorcerer's Stone",
                     'Harry Potter and the Deathly Hallows Part 2',
                     'Jackass 3-D',
                     'GoldenEye',
                     'The World Is Not Enough',
                     'Jaws IV: The Revenge',
                     'Jaws 3-D',
                     'Jeepers Creepers 2',
                     'The Karate Kid Part III',
                     'The Karate Kid Part II',
                     'King Kong Lives',
                     'Blade II',
                     "Bridget Jones's Baby",
                     'Bridget Jones: The Edge of Reason',
                     '3 Ninjas: High Noon at Mega Mountain',
                     '3 Ninjas Knuckle Up',
                     '3 Ninjas',
                     'Aces: Iron Eagle III',
                     'Ip Man: The Final Fight',
                     'Raiders of the Lost Ark (Re-issue) (1983)',
                     'An Inconvenient Sequel: Truth to Power',
                     'House Party 3',
                     'Home Alone 3',
                     'Hellraiser 4: Bloodline',
                     'Hellbound: Hellraiser II',
                     'Hellraiser III: Hell on Earth',
                     'Highlander 2: The Quickening',
                     'House Party',
                     'Raiders of the Lost Ark (Re-issue) (1982)',
                     'Ip Man 2: Legend of the Grandmaster',
                     'Ip Man 3',
                     'Iron Eagle II',
                     'Iron Eagle',
                     'Harold and Kumar Go to White Castle',
                     'Manhunter',
                     'The Hangover Part III',
                     'Halloween 5',
                     'Halloween III: Season of the Witch',
                     'Godzilla (2014)',
                     'The Godfather (Re-issue)',
                     "God's Not Dead 2",
                     'Ghostbusters (30th Anniversary re-release)',
                     'Fright Night II',
                     'Free Willy 3: The Rescue',
                     'Free Willy 2: The Adventure Home',
                     'Friday the 13th Part VII',
                     'Friday the 13th Part VI',
                     'Friday the 13th - Part V',
                     'Friday the 13th: Final Chapter',
                     'Friday the 13th Part III',
                     'Friday the 13th (2009)',
                     'Fright Night (2011)',
                     'Ghostbusters (Re-issue)',
                     'Ghostbusters II',
                     'Ghostbusters (2016)',
                     "God's Not Dead",
                     'The Godfather Part III',
                     'Halloween II (2009)',
                     'Halloween: H20',
                     'Halloween (2007)',
                     'Harold and Kumar Escape from Guantanamo Bay',
                     'Dominion: Prequel to the Exorcist',
                     'Evangelion 1.0 You Are (Not) Alone',
                     'The Mummy (2017)',
                     'Conan the Barbarian (2011)',
                     'The Conjuring 2',
                     'Crocodile Dundee II',
                     'Evangelion 2.0: You Can (Not) Advance',
                     'Evangelion: 3.0 You Can (Not) Redo',
                     'Evil Dead 2',
                     'Evil Dead (2013)',
                     'The Exorcist III',
                     "The Exorcist Director's Cut",
                     'Fantastic Four (2005)',
                     'Fast and Furious',
                     'The Care Bears Movie 3',
                     'The Care Bears Movie 2',
                     'The Care Bears Movie ',
                     "Child's Play 3",
                     'Fast & Furious 6',
                     'Godzilla (Original Japanese Version)',
                     'Shin Godzilla',
                     'Godzilla 1985']
        for i,movie in enumerate(Movies_pg_list):
            print(i, movie)
            first = '//table/tr[' + str(2*(i+1))
            for MissMovie in Miss_list:
                if difflib.SequenceMatcher(None,MissMovie,movie).ratio()>0.85: 
                    yield {
                          'url': url,
                          'MovieNumbers' : response.xpath(first+']/td/b/a/text()').extract(), 
                          'MovieBOM': MissMovie, 
                          'Budget': response.xpath(first+']/td[@ class ="data"][2]/text()').extract(),
                          'Rel_Date': response.xpath(first+']/td/a/text()').extract(),
                          'Dom_Gross': response.xpath(first+']/td[@ class ="data"][3]/text()').extract(), 
                          'Wor_Gross': response.xpath(first+']/td[@ class ="data"][4]/text()').extract()    
                    }
 
                
            
                
             
        
        