import scrapy


class BudgetSpider(scrapy.Spider):

    name = 'budget_data'

    custom_settings = {
        "DOWNLOAD_DELAY": 3,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 3,
        "HTTPCACHE_ENABLED": True
    }
    # Page it begins scraping
    start_urls = ['http://www.the-numbers.com/movie/budgets/all']
    
    def parse(self, response):
        for i in range(1,5402,100):         
            url = 'http://www.the-numbers.com/movie/budgets/all/'
            yield scrapy.Request(
                url = 'http://www.the-numbers.com/movie/budgets/all/' + str(i),  #url for each new movie page
                callback = self.parse_movie_list,       #calls method below to extract data from each movie pg
                meta={'url': url}
                )
 
       
    def parse_movie_list(self, response):
        # searches if each movie on the page is in missing list, if it is then it copies the details
        #once it finishes a page it goes back to method parse
        url = response.request.meta['url']
        Movies_pg_list = response.xpath('//table/tr/td/b/a/text()').extract() 
        print(Movies_pg_list)
        Miss_list = ['The Transporter Refueled',
                     'The Transporter',
                     'Transporter 3',
                     'Transporter 2',
                     'The Trip (2011)',
                     'The Trip to Italy',
                     'Trolls',
                     'Twilight',
                     'The Twilight Saga: Breaking Dawn Part 1',
                     'The Twilight Saga: Breaking Dawn Part 2',
                     'The Twilight Saga: New Moon',
                     'The Twilight Saga: Eclipse',
                     'Alex Cross',
                     '300: Rise of An Empire',
                     'Ernest Rides Again',
                     'El Mariachi',
                     'Earth (2009)',
                     'Dumb and Dumberer: When Harry Met Lloyd',
                     'Dolphin Tale 2',
                     'The Divergent Series: Allegiant',
                     'Cinderella (2015)',
                     'A Good Day to Die Hard',
                     'Diary of a Wimpy Kid: The Long Haul',
                     'Despicable Me',
                     'Transformers: The Movie',
                     'Transformers: The Last Knight',
                     'Transformers: Age of Extinction',
                     'Transformers',
                     'Transformers: Dark of the Moon',
                     'Transformers: Revenge of the Fallen',
                     'Minions',
                     'Despicable Me 2',
                     'Dhoom 2',
                     'Dhoom 3',
                     'Diary of a Wimpy Kid: Dog Days',
                     'Diary of a Wimpy Kid: Rodrick Rules',
                     'Diary of a Wimpy Kid',
                     'Die Hard',
                     'Die Hard: With A Vengeance',
                     'Die Hard 2: Die Harder',
                     'Live Free or Die Hard',
                     'The Dead Pool',
                     'Sudden Impact',
                     'Oz The Great and Powerful',
                     'Maleficent',
                     'The Jungle Book (2016)',
                     'Underworld: Blood Wars',
                     'Beauty and the Beast (2017)',
                     'The Divergent Series: Insurgent',
                     'Divergent',
                     'Dolphin Tale',
                     'Universal Soldier: Day of Reckoning',
                     'Dumb and Dumber To',
                     'Dumb and Dumber',
                     'V/H/S: Viral',
                     'Desperado',
                     'Once Upon a Time in Mexico',
                     'Vegas Vacation',
                     'Ernest Scared Stupid',
                     'Ernest Goes to Camp',
                     'Ernest Goes to Jail',
                     'Ernest Saves Christmas',
                     'Mallrats',
                     '300',
                     'Kiss the Girls',
                     'Along Came a Spider',
                     'Underworld: Rise of the Lycans',
                     'Underworld',
                     'Underworld: Evolution',
                     'Underworld Awakening',
                     'Universal Soldier: The Return',
                     'Universal Soldier',
                     'V/H/S',
                     'The Woman in Black 2: Angel of Death',
                     'The Woman in Black',
                     'The Wolverine',
                     'European Vacation',
                     'Vacation',
                     "National Lampoon's Vacation",
                     'Christmas Vacation',
                     'Clerks',
                     'Chasing Amy',
                     'Clerks II',
                     'Jay and Silent Bob Strike Back',
                     'The Work and the Glory III: A House Divided',
                     'Dogma',
                     "Pooh's Heffalump Movie",
                     'World War Z',
                     "Piglet's Big Movie",
                     'XXX: State of the Union',
                     'Winnie the Pooh',
                     'The Tigger Movie',
                     'Zoolander 2',
                     'Zoolander',
                     'Race to Witch Mountain',
                     'X-Men: First Class',
                     'X-Men: Apocalypse',
                     'X-Men',
                     'X-Men Origins: Wolverine',
                     'X2: X-Men United',
                     'Logan',
                     'X-Men: Days of Future Past',
                     'X-Men: The Last Stand',
                     'The Work and the Glory II: American Zion',
                     'The Work and the Glory',
                     'Deadpool',
                     'xXx: The Return of Xander Cage',
                     'XXX',
                     'Alice Through the Looking Glass',
                     'Alice in Wonderland (2010)',
                     'Toy Story / Toy Story 2 (3D)',
                     'Shaun of the Dead',
                     'Thor',
                     'Return of the Texas Chainsaw Massacre',
                     'The Terminator',
                     'Teenage Mutant Ninja Turtles III',
                     'Ted 2',
                     'Taken 3',
                     'Superman IV: The Quest for Peace',
                     'Super Troopers',
                     'Step Up All In',
                     'Rogue One: A Star Wars Story',
                     'Attack of the Clones: The IMAX Experience (IMAX)',
                     'Spy Kids: All the Time in the World',
                     'The SpongeBob SquarePants Movie',
                     'The SpongeBob Movie: Sponge Out of Water',
                     'Spy Kids 2: The Island of Lost Dreams',
                     'Spy Kids 3D: Game Over',
                     'Spy Kids',
                     'Star Trek V: The Final Frontier',
                     'Star Trek: Insurrection',
                     'Star Trek VI: The Undiscovered Country',
                     'Star Trek: Generations',
                     'Star Trek III: The Search for Spock',
                     'Star Trek II: The Wrath of Khan',
                     'Star Trek: The Motion Picture',
                     'Star Trek: First Contact',
                     'Star Trek IV: The Voyage Home',
                     'Star Trek Beyond',
                     'Star Trek Into Darkness',
                     'Star Trek',
                     'Return of the Jedi (Re-issue)',
                     'The Empire Strikes Back (Re-issue)',
                     'Star Wars (Re-issue)',
                     'Star Wars: The Clone Wars',
                     'Star Wars: Episode I - The Phantom Menace (in 3D)',
                     'Return of the Jedi (Special Edition)',
                     'The Empire Strikes Back (Special Edition)',
                     'Star Wars (Special Edition)',
                     'The Empire Strikes Back',
                     'Return of the Jedi',
                     'Star Wars: Episode II - Attack of the Clones',
                     'Star Wars',
                     'Star Wars: Episode III - Revenge of the Sith',
                     'Star Wars: Episode I - The Phantom Menace',
                     'Star Wars: The Force Awakens',
                     'Step Up Revolution',
                     'Step Up 3-D',
                     'Step Up 2 the Streets',
                     'Step Up',
                     'Superman III',
                     'Superman II',
                     'Superman',
                     'Superman Returns',
                     'Man of Steel',
                     'Taken 2',
                     'Taken',
                     'Ted',
                     'TMNT',
                     'Teenage Mutant Ninja Turtles II',
                     'Teenage Mutant Ninja Turtles: Out of the Shadows',
                     'Teenage Mutant Ninja Turtles',
                     'Teenage Mutant Ninja Turtles (2014)',
                     'Terminator: Genisys',
                     'Terminator Salvation',
                     'Terminator 3: Rise of the Machines',
                     'Terminator 2: Judgment Day',
                     'Texas Chainsaw Massacre: The Next Generation',
                     'Leatherface: The Texas Chainsaw Massacre III',
                     'The Texas Chainsaw Massacre 2',
                     'Texas Chainsaw 3D',
                     'The Texas Chainsaw Massacre: The Beginning',
                     'The Texas Chainsaw Massacre',
                     'Thor: The Dark World',
                     'Hot Fuzz',
                     "The World's End",
                     'Toy Story',
                     'Toy Story 2',
                     'Toy Story 3',
                     'The Amazing Spider-Man 2',
                     "The Huntsman: Winter's War",
                     'The Smurfs and the Magic Flute',
                     'Smokey & the Bandit Part III',
                     'Sinister 2',
                     'Sing',
                     "Frank Miller's Sin City: A Dame to Kill For",
                     'Sicario',
                     'Puss in Boots',
                     'Shiloh 2: Shiloh Season',
                     'The Secret Life of Pets',
                     'Scream 4',
                     'Scooby-Doo 2: Monsters Unleashed',
                     'Scary Movie 5',
                     'Saw VI',
                     'The Santa Clause 3: The Escape Clause',
                     'Rush Hour 3',
                     'Rush Hour',
                     'Rush Hour 2',
                     'The Santa Clause 2',
                     'The Santa Clause',
                     'Saw 3D',
                     'Saw',
                     'Saw V',
                     'Saw IV',
                     'Saw III',
                     'Saw II',
                     'Scary Movie 2',
                     'Scary Movie 4',
                     'Scary Movie 3',
                     'Scary Movie',
                     'Scooby-Doo',
                     'Scream 3',
                     'Scream 2',
                     'Scream',
                     'Shiloh',
                     'Shrek Forever After',
                     'Shrek',
                     'Shrek the Third',
                     'Shrek 2',
                     'Sin City',
                     'Sinister',
                     'Smurfs: The Lost Village',
                     'The Smurfs 2',
                     'The Smurfs',
                     'Snow White and the Huntsman',
                     'The Amazing Spider-Man',
                     'Spider-Man 3',
                     'Spider-Man 2',
                     'Spider-Man',
                     'Rugrats Go Wild',
                     'Rocky III (Re-issue)',
                     'Robocop 3',
                     'Inferno',
                     'Rio 2',
                     'Rings',
                     'Ride Along 2',
                     'Pitch Black',
                     'Resident Evil: The Final Chapter',
                     'Red 2',
                     'Rambo',
                     'The Raid 2',
                     'The Purge',
                     'Psycho III',
                     'Predator 2',
                     'Turbo: A Power Rangers Movie',
                     "Mighty Morphin' Power Rangers",
                     'Power Rangers (2017)',
                     'Predators',
                     'Predator',
                     'Psycho (1998)',
                     'Psycho II',
                     'The Purge: Anarchy',
                     'The Purge: Election Year',
                     'The Raid: Redemption',
                     'First Blood',
                     'Rambo III',
                     'Rambo: First Blood Part II',
                     'Red',
                     'Resident Evil',
                     'Resident Evil: Retribution',
                     'Resident Evil: Extinction',
                     'Resident Evil: Apocalypse',
                     'Resident Evil: Afterlife',
                     'Return of the Living Dead III',
                     'Return of the Living Dead 2',
                     'Return of the Living Dead',
                     'Riddick',
                     'The Chronicles of Riddick',
                     'Ride Along',
                     'The Ring Two',
                     'The Ring',
                     'Rio',
                     'Angels & Demons',
                     'The Da Vinci Code',
                     'Robocop 2',
                     'Robocop',
                     'RoboCop (2014)',
                     'Rocky V',
                     'Rocky Balboa',
                     'Creed',
                     'Rocky III',
                     'Rocky IV',
                     'Rugrats in Paris: The Movie',
                     'The Rugrats Movie',
                     'Aliens Vs. Predator - Requiem',
                     'Alien Resurrection',
                     'Alien 3',
                     'Alien: Covenant',
                     'Alien',
                     'Alien Vs. Predator',
                     'Aliens',
                     'Prometheus',
                     "Porky's (Re-issue)",
                     'Pokemon Heroes',
                     'Pitch Perfect',
                     'Pirates of the Caribbean: Dead Men Tell No Tales',
                     'Son of the Pink Panther',
                     'Paul Blart: Mall Cop 2',
                     'Paranormal Activity: The Ghost Dimension',
                     'Pacific Rim',
                     'Ouija: Origin of Evil',
                     'Ong Bak 3',
                     'Damien: The Omen Part II',
                     'The Omen (2006)',
                     'The Omen',
                     'Ong Bak 2: The Beginning',
                     'Ong Bak: The Thai Warrior',
                     'Ouija',
                     'Paranormal Activity: The Marked Ones',
                     'Paranormal Activity 4',
                     'Paranormal Activity 2',
                     'Paranormal Activity 3',
                     'Paranormal Activity',
                     'Paul Blart: Mall Cop',
                     'Curse of the Pink Panther',
                     'Trail of the Pink Panther',
                     'The Pink Panther 2',
                     'The Pink Panther (2006)',
                     'Pirates of the Caribbean: On Stranger Tides',
                     'Pirates of the Caribbean: The Curse of the Black Pearl',
                     "Pirates of the Caribbean: At World's End",
                     "Pirates of the Caribbean: Dead Man's Chest",
                     'Pitch Perfect 2',
                     'Planet of the Apes',
                     'Planet of the Apes (2001)',
                     'Dawn of the Planet of the Apes',
                     'Pokemon 4Ever',
                     'Pokemon 3: The Movie',
                     'The Chipmunk Adventure',
                     'Pokemon: The Movie 2000',
                     'Pokemon: The First Movie',
                     'Police Academy 6: City Under Siege',
                     'Police Academy 5: Assignment:',
                     'American Ninja 4: The Annihilation',
                     'Police Academy 4: Citizens on Patrol',
                     'Police Academy 3: Back in Training',
                     'Police Academy 2: Their First Assignment',
                     'American Reunion',
                     'Police Academy',
                     'Poltergeist III',
                     'Poltergeist II: The Other Side',
                     'Amityville 3-D',
                     'Poltergeist (2015)',
                     'Poltergeist',
                     "Porky's Revenge (Part III)",
                     'The Angry Birds Movie',
                     'Batman: Mask of the Phantasm',
                     'Arthur 2: On the Rocks',
                     "Porky's II: The Next Day",
                     "Porky's",
                     'Alvin and the Chipmunks: The Road Chip',
                     'Alvin and the Chipmunks: Chipwrecked',
                     'Alvin and the Chipmunks',
                     'Alvin and the Chipmunks: The Squeakquel',
                     'American Ninja 3: Blood Hunt',
                     'American Ninja 2',
                     'American Ninja',
                     'American Pie',
                     'American Wedding',
                     'American Pie 2',
                     'Amityville II: The Possession',
                     'The Amityville Horror (2005)',
                     'The Amityville Horror',
                     'Arthur (2011)',
                     'Arthur',
                     "Ocean's Thirteen",
                     'Now You See Me 2',
                     "Wes Craven's New Nightmare",
                     'Night at the Museum: Secret of the Tomb',
                     'Neighbors 2: Sorority Rising',
                     'The Naked Gun 33 1/3: The Final Insult',
                     'My Big Fat Greek Wedding 2',
                     'Muppets from Space',
                     'The Scorpion King',
                     'Monsters, Inc.',
                     'Mission: Impossible III',
                     'Braddock: Missing in Action III',
                     'Missing in Action II: The Beginning',
                     "The Girl Who Kicked the Hornet's Nest",
                     'D3: The Mighty Ducks',
                     'D2: The Mighty Ducks',
                     'The Mighty Ducks',
                     'The Girl Who Played with Fire',
                     'The Girl with the Dragon Tattoo',
                     'Missing in Action',
                     'Mission: Impossible',
                     'Mission: Impossible - Rogue Nation',
                     'Mission: Impossible - Ghost Protocol',
                     'Mission: Impossible II',
                     'Monsters University',
                     'The Mummy: Tomb of the Dragon Emperor',
                     'The Mummy',
                     'The Mummy Returns',
                     'The Muppets Take Manhattan',
                     'The Muppet Christmas Carol',
                     'Muppet Treasure Island',
                     'Muppets Most Wanted',
                     'The Muppets',
                     'My Big Fat Greek Wedding',
                     'The Naked Gun: From the Files of Police Squad!',
                     'The Naked Gun 2 1/2: The Smell of Fear',
                     'Neighbors',
                     'The Neverending Story II',
                     'The Neverending Story',
                     'Night at the Museum: Battle of the Smithsonian',
                     'Night at the Museum',
                     'A Nightmare on Elm Street 5: The Dream Child',
                     'A Nightmare on Elm Street',
                     "A Nightmare on Elm Street 2: Freddy's Revenge",
                     "Freddy's Dead: The Final Nightmare",
                     'A Nightmare on Elm Street 3: Dream Warriors',
                     'A Nightmare on Elm Street 4: The Dream Master',
                     'A Nightmare on Elm Street (2010)',
                     'Freddy Vs. Jason',
                     'Now You See Me',
                     "Ocean's Twelve",
                     "Ocean's Eleven",
                     'Oh, God! You Devil!',
                     'Oh, God!',
                     'Atlas Shrugged Part III: Who Is John Galt?',
                     'Atlas Shrugged: Part II',
                     'The Hobbit: The Battle of the Five Armies',
                     'MIB 3',
                     'The Giant Mechanical Man',
                     'Maze Runner: The Scorch Trials',
                     'The Matrix Revolutions',
                     'Major League: Back to the Minors',
                     "Tyler Perry's Diary of a Mad Black Woman",
                     'Penguins of Madagascar',
                     'Machete Kills',
                     'The Lord of the Rings (1978)',
                     "Look Who's Talking Now",
                     'Lethal Weapon',
                     'The LEGO Movie',
                     'Lethal Weapon 4',
                     'Lethal Weapon 3',
                     'Lethal Weapon 2',
                     "Look Who's Talking Too",
                     "Look Who's Talking",
                     'Machete',
                     'Captain America: The First Avenger',
                     'The Road Warrior',
                     'Mad Max Beyond Thunderdome',
                     'Captain America: The Winter Soldier',
                     'Mad Max: Fury Road',
                     'Madagascar: Escape 2 Africa',
                     'Madagascar',
                     "Madagascar 3: Europe's Most Wanted",
                     'Captain America: Civil War',
                     "Tyler Perry's A Madea Christmas",
                     "Tyler Perry's Madea's Big Happy Family",
                     "Tyler Perry's Madea's Family Reunion",
                     "Tyler Perry's Madea's Witness Protection",
                     'Boo! A Madea Halloween',
                     "Tyler Perry's Madea Goes to Jail",
                     'Major League II',
                     'Major League',
                     'The Incredible Hulk',
                     'Ant-Man',
                     'Doctor Strange',
                     'Iron Man 2',
                     'Iron Man',
                     'Guardians of the Galaxy',
                     'Guardians of the Galaxy Vol. 2',
                     'Austin Powers: International Man of Mystery',
                     'Iron Man 3',
                     'The Matrix',
                     'Avatar: Special Edition',
                     'The Matrix Reloaded',
                     'Avengers: Age of Ultron',
                     'The Maze Runner',
                     'Back to the Future Part III',
                     'Meatballs II',
                     'Bad Boys',
                     'Mechanic: Resurrection',
                     'Bad Moms',
                     'Men in Black II',
                     'Men in Black',
                     'The Hobbit: The Desolation of Smaug',
                     'The Hobbit: An Unexpected Journey',
                     'The Lord of the Rings: The Fellowship of the Ring',
                     'The Lord of the Rings: The Two Towers',
                     'The Lord of the Rings: The Return of the King',
                     'Batman and Robin',
                     'Batman Returns',
                     'The LEGO Batman Movie',
                     'Batman Forever',
                     'Batman Begins',
                     'Batman',
                     'Batman v Superman: Dawn of Justice',
                     'The Dark Knight Rises',
                     'The Dark Knight',
                     'Before Sunrise',
                     'Before Sunset',
                     'Before Midnight',
                     'Benji Off the Leash',
                     'Benji the Hunted',
                     'The Best Man',
                     'The Best Man Holiday',
                     'Atlas Shrugged: Part I',
                     'Austin Powers: The Spy Who Shagged Me',
                     'Austin Powers in Goldmember',
                     'Avatar',
                     "Marvel's The Avengers",
                     'Back to the Future Part II',
                     'Back to the Future',
                     'Bad Boys II',
                     'The Bad News Bears',
                     'Bad News Bears',
                     'Beauty Shop',
                     'Barbershop: The Next Cut',
                     'Barbershop 2: Back in Business',
                     'Barbershop',
                     'Kung Fu Panda 3',
                     'Kick-Ass 2',
                     'The Next Karate Kid',
                     'Jurassic Park III',
                     '21 Jump Street',
                     'Johnny English Reborn',
                     'John Wick',
                     'Jaws 2 (1980 re-issue)',
                     'Jackass: The Movie',
                     'Jack Ryan: Shadow Recruit',
                     'Jack Reacher: Never Go Back',
                     'Harry Potter IMAX Marathon',
                     'Fantastic Beasts and Where To Find Them',
                     'Harry Potter and the Prisoner of Azkaban',
                     'Harry Potter and the Chamber of Secrets',
                     'Harry Potter and the Goblet of Fire',
                     'Harry Potter and the Order of the Phoenix',
                     'Harry Potter and the Deathly Hallows Part 1',
                     'Harry Potter and the Half-Blood Prince',
                     "Harry Potter and the Sorcerer's Stone",
                     'Harry Potter and the Deathly Hallows Part 2',
                     'Jack Reacher',
                     'Patriot Games',
                     'The Sum of All Fears',
                     'The Hunt for Red October',
                     'Clear and Present Danger',
                     'Jackass: Number Two',
                     'Jackass Presents: Bad Grandpa',
                     'Jackass 3-D',
                     'Licence to Kill',
                     'A View to a Kill',
                     'The Living Daylights',
                     'Never Say Never Again',
                     'Octopussy',
                     'Moonraker',
                     'GoldenEye',
                     'Tomorrow Never Dies',
                     'The World Is Not Enough',
                     'Die Another Day',
                     'Casino Royale',
                     'Quantum of Solace',
                     'Spectre',
                     'Skyfall',
                     'Jaws IV: The Revenge',
                     'Jaws 3-D',
                     'Jaws 2',
                     'Jaws',
                     'Jeepers Creepers 2',
                     'Jeepers Creepers',
                     'John Wick: Chapter Two',
                     'Johnny English',
                     '22 Jump Street',
                     'The Lost World: Jurassic Park',
                     'Jurassic Park',
                     'Jurassic World',
                     'The Karate Kid Part III',
                     'The Karate Kid',
                     'The Karate Kid Part II',
                     'The Karate Kid',
                     'Kick-Ass',
                     'King Kong Lives',
                     'Kong: Skull Island',
                     'King Kong',
                     'Kingsman: The Secret Service',
                     'Kung Fu Panda 2',
                     'Kung Fu Panda',
                     'Beverly Hills Cop III',
                     'Beverly Hills Cop II',
                     'Beverly Hills Cop',
                     'Big Mommas: Like Father, Like Son',
                     "Big Momma's House 2",
                     "Big Momma's House",
                     'Blade: Trinity',
                     'Blade',
                     'Blade II',
                     'Blair Witch',
                     'Book of Shadows: Blair Witch 2',
                     'The Blair Witch Project',
                     'The Bourne Legacy',
                     'The Bourne Identity',
                     'Jason Bourne',
                     'The Bourne Supremacy',
                     'The Bourne Ultimatum',
                     "Bridget Jones's Baby",
                     'Bridget Jones: The Edge of Reason',
                     "Bridget Jones's Diary",
                     '3 Ninjas: High Noon at Mega Mountain',
                     '3 Ninjas Knuckle Up',
                     '3 Ninjas Kick Back',
                     '3 Ninjas',
                     'Aces: Iron Eagle III',
                     'Ip Man: The Final Fight',
                     'Insidious Chapter 3',
                     'Raiders of the Lost Ark (Re-issue) (1983)',
                     'Independence Day: Resurgence',
                     'An Inconvenient Sequel: Truth to Power',
                     'Ice Age: Collision Course',
                     'The Hunger Games: Mockingjay - Part 2',
                     'How to Train Your Dragon 2',
                     'House Party 3',
                     'Hotel Transylvania',
                     'Hot Tub Time Machine 2',
                     'Home Alone 3',
                     'Home Alone 2: Lost in New York',
                     'Highlander',
                     'Hellraiser 4: Bloodline',
                     'Hellbound: Hellraiser II',
                     'Hellraiser III: Hell on Earth',
                     'Hellraiser',
                     'Herbie: Fully Loaded',
                     'Highlander: Endgame',
                     'Highlander 2: The Quickening',
                     'Home Alone',
                     'Hot Tub Time Machine',
                     'Hotel Transylvania 2',
                     'House Party 2',
                     'House Party',
                     'How to Train Your Dragon',
                     'The Hunger Games: Mockingjay - Part 1',
                     'The Hunger Games',
                     'The Hunger Games: Catching Fire',
                     'Ice Age: Continental Drift',
                     'Ice Age',
                     'Ice Age: The Meltdown',
                     'Ice Age: Dawn of the Dinosaurs',
                     'An Inconvenient Truth',
                     'Independence Day',
                     'Raiders of the Lost Ark (Re-issue) (1982)',
                     'Indiana Jones and the Temple of Doom',
                     'Indiana Jones and the Last Crusade',
                     'Raiders of the Lost Ark',
                     'Indiana Jones and the Kingdom of the Crystal Skull',
                     'Insidious',
                     'Insidious Chapter 2',
                     'Ip Man 2: Legend of the Grandmaster',
                     'Ip Man 3',
                     'Iron Eagle II',
                     'Iron Eagle',
                     'A Haunted House 2',
                     'A Haunted House',
                     'Harold and Kumar Go to White Castle',
                     'Manhunter',
                     'The Hangover Part III',
                     'Halloween 5',
                     'Halloween III: Season of the Witch',
                     'Grown Ups 2',
                     'Godzilla (2014)',
                     'Grown Ups',
                     'The Godfather (Re-issue)',
                     "God's Not Dead 2",
                     'Ghostbusters (30th Anniversary re-release)',
                     'Fright Night II',
                     'Friday',
                     'Free Willy 3: The Rescue',
                     'Free Willy 2: The Adventure Home',
                     'Free Willy',
                     'Friday After Next',
                     'Next Friday',
                     'Jason Goes to Hell: The Final Friday',
                     'Friday the 13th Part VII',
                     'Friday the 13th Part VI',
                     'Friday the 13th - Part V',
                     'Friday the 13th: Final Chapter',
                     'Friday the 13th Part III',
                     'Friday the 13th (2009)',
                     'Fright Night (2011)',
                     'Fright Night',
                     'Ghostbusters (Re-issue)',
                     'Ghostbusters II',
                     'Ghostbusters (2016)',
                     'Ghostbusters',
                     "God's Not Dead",
                     'The Godfather Part III',
                     'The Godfather',
                     'Halloween: The Curse of Michael Myers',
                     'Halloween 4: The Return of Michael Myers',
                     'Halloween: Resurrection',
                     'Halloween II (2009)',
                     'Halloween',
                     'Halloween: H20',
                     'Halloween (2007)',
                     'The Hangover Part II',
                     'The Hangover',
                     'Hannibal Rising',
                     'Red Dragon',
                     'The Silence of the Lambs',
                     'Hannibal',
                     'A Very Harold & Kumar 3D Christmas',
                     'Harold and Kumar Escape from Guantanamo Bay',
                     'Little Fockers',
                     'Finding Nemo',
                     'Final Destination 5',
                     'Fifty Shades Darker',
                     'The Fast and the Furious: Tokyo Drift',
                     'Fantastic Four',
                     'Fantastic Four: Rise of the Silver Surfer',
                     'The Expendables 3',
                     'Dominion: Prequel to the Exorcist',
                     'The Evil Dead',
                     'Evangelion 1.0 You Are (Not) Alone',
                     'Suicide Squad',
                     'The Mummy (2017)',
                     'Crocodile Dundee in Los Angeles',
                     'Annabelle',
                     'Conan the Barbarian (2011)',
                     'Conan the Destroyer',
                     'Conan the Barbarian',
                     'The Conjuring 2',
                     'The Conjuring',
                     'Crocodile Dundee II',
                     'Crocodile Dundee',
                     'Evangelion 2.0: You Can (Not) Advance',
                     'Evangelion: 3.0 You Can (Not) Redo',
                     'Evil Dead 2',
                     'Army of Darkness',
                     'Evil Dead (2013)',
                     'The Exorcist III',
                     'Exorcist II: The Heretic',
                     "The Exorcist Director's Cut",
                     'Exorcist: The Beginning',
                     'The Exorcist',
                     'The Expendables 2',
                     'The Expendables',
                     'Fantastic Four (2005)',
                     '2 Fast 2 Furious',
                     'The Fast and the Furious',
                     'Fast and Furious',
                     'The Care Bears Movie 3',
                     'The Care Bears Movie 2',
                     'The Care Bears Movie ',
                     'Cars 2',
                     'Cars',
                     "Child's Play 3",
                     'Seed of Chucky',
                     "Child's Play 2",
                     'Bride of Chucky',
                     "Child's Play",
                     'The Chronicles of Narnia: The Voyage of the Dawn Treader',
                     'The Chronicles of Narnia: Prince Caspian',
                     'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
                     'Fast Five',
                     'The Fate of the Furious',
                     'Fast & Furious 6',
                     'Furious 7',
                     'Fifty Shades of Grey',
                     'Final Destination 2',
                     'Final Destination',
                     'Final Destination 3',
                     'The Final Destination',
                     'Finding Dory',
                     'Meet the Parents',
                     'Meet the Fockers',
                     '10 Cloverfield Lane',
                     'Cloverfield',
                     'Cloudy with a Chance of Meatballs 2',
                     'Cloudy with a Chance of Meatballs',
                     'Godzilla (Original Japanese Version)',
                     'Shin Godzilla',
                     'Godzilla 1985',
                     'Godzilla 2000',
                     'Godzilla']
        for i,movie in enumerate(Movies_pg_list):
            print(i, movie)
            first = '//table/tr[' + str(2*(i+1))
            if movie in Miss_list:
                yield {
                      'url': url,
                      'Movie' : response.xpath(first+']/td/b/a/text()').extract(), 
                      'Budget': response.xpath(first+']/td[@ class ="data"][2]/text()').extract(),
                      'Rel_Date': response.xpath(first+']/td/a/text()').extract(),
                      'Dom_Gross': response.xpath(first+']/td[@ class ="data"][3]/text()').extract(), 
                      'Wor_Gross': response.xpath(first+']/td[@ class ="data"][4]/text()').extract()    
                }
                    
             
        
        