import scrapy


class DirBudgetSpider(scrapy.Spider):

    name = 'DirBudget_data'

    custom_settings = {
        "DOWNLOAD_DELAY": 3,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 3,
        "HTTPCACHE_ENABLED": True
    }
    # Page it begins scraping
    start_urls = ['http://www.the-numbers.com/movie/budgets/all']
    
    def parse(self, response):
        for i in range(1,5402,100):         
            url = 'http://www.the-numbers.com/movie/budgets/all/'
            yield scrapy.Request(
                url = 'http://www.the-numbers.com/movie/budgets/all/' + str(i),  #url for each new movie page
                callback = self.parse_movie_list,       #calls method below to extract data from each movie pg
                meta={'url': url}
                )
 
       
    def parse_movie_list(self, response):
        # searches if each movie on the page is in missing list, if it is then it copies the details
        #once it finishes a page it goes back to method parse
        url = response.request.meta['url']
        Movies_pg_list = response.xpath('//table/tr/td/b/a/text()').extract() 
        print(Movies_pg_list)
        Miss_list = ['3 Ninjas',
                     '3 Ninjas Kick Back',
                     '3 Ninjas Knuckle Up',
                     '3 Ninjas: High Noon at Mega Mountain',
                     'Blade II',
                     'Blade',
                     'Blade: Trinity',
                     "Big Momma's House",
                     "Big Momma's House 2",
                     'Big Mommas: Like Father, Like Son',
                     'Beverly Hills Cop',
                     'Beverly Hills Cop II',
                     'Beverly Hills Cop III',
                     'The Best Man Holiday',
                     'The Best Man',
                     'Benji',
                     'Benji the Hunted',
                     'For the Love of Benji',
                     'Oh, Heavenly Dog!',
                     'Before Midnight',
                     'Before Sunset',
                     'Before Sunrise',
                     'The Dark Knight',
                     'Barbershop',
                     'Barbershop 2: Back in Business',
                     'Barbershop: The Next Cut',
                     'Beauty Shop',
                     'Bad News Bears',
                     'The Bad News Bears',
                     'Bad Moms',
                     'Bad Boys II',
                     'Bad Boys',
                     'Back to the Future',
                     'Back to the Future Part II',
                     'Back to the Future Part III',
                     "Marvel's The Avengers",
                     'Avengers: Age of Ultron',
                     'Avatar',
                     'Avatar: Special Edition',
                     'Austin Powers in Goldmember',
                     'Austin Powers: The Spy Who Shagged Me',
                     'Austin Powers: International Man of Mystery',
                     'The Dark Knight Rises',
                     'Batman v Superman: Dawn of Justice',
                     'Batman',
                     'Batman Begins',
                     'Batman Forever',
                     'The LEGO Batman Movie',
                     'Batman Returns',
                     'Batman and Robin',
                     'Batman: Mask of the Phantasm',
                     'Batman: The Killing Joke',
                     'Atlas Shrugged: Part I',
                     'Atlas Shrugged: Part II',
                     'Atlas Shrugged Part III: Who Is John Galt?',
                     '300',
                     '300: Rise of An Empire',
                     'Arthur',
                     'Arthur (2011)',
                     'Arthur 2: On the Rocks',
                     'Zoolander',
                     'Zoolander 2',
                     'XXX',
                     'xXx: The Return of Xander Cage',
                     'XXX: State of the Union',
                     'Deadpool',
                     'World War Z',
                     'The Work and the Glory',
                     'The Work and the Glory II: American Zion',
                     'The Work and the Glory III: A House Divided',
                     'Wonder Woman',
                     'The Woman in Black',
                     'The Woman in Black 2: Angel of Death',
                     'Logan',
                     'X-Men Origins: Wolverine',
                     'The Wolverine',
                     'Race to Witch Mountain',
                     'Escape to Witch Mountain',
                     'The Tigger Movie',
                     'Winnie the Pooh',
                     "Piglet's Big Movie",
                     "Pooh's Heffalump Movie",
                     'The Many Adventures of Winnie the Pooh',
                     'Dogma',
                     'Jay and Silent Bob Strike Back',
                     'Clerks II',
                     'Chasing Amy',
                     'Clerks',
                     'Mallrats',
                     'X-Men: The Last Stand',
                     'X-Men: Days of Future Past',
                     'Logan',
                     'X2: X-Men United',
                     'X-Men Origins: Wolverine',
                     'X-Men',
                     'X-Men: Apocalypse',
                     'X-Men: First Class',
                     'The Wolverine',
                     'Return of the Living Dead',
                     'Return of the Living Dead 2',
                     'Return of the Living Dead III',
                     'Dead 5: Rave to the Grave',
                     'Resident Evil: Afterlife',
                     'Resident Evil: Apocalypse',
                     'Resident Evil: Extinction',
                     'Resident Evil: Retribution',
                     'Resident Evil',
                     'Red',
                     'Red 2',
                     'Resident Evil: The Final Chapter',
                     'The Angry Birds Movie',
                     'The Amityville Horror',
                     'The Amityville Horror (2005)',
                     'Amityville II: The Possession',
                     'Amityville 3-D',
                     'American Pie 2',
                     'American Wedding',
                     'American Pie',
                     'American Reunion',
                     'American Ninja',
                     'American Ninja 2',
                     'American Ninja 3: Blood Hunt',
                     'American Ninja 4: The Annihilation',
                     'Alvin and the Chipmunks: The Squeakquel',
                     'Alvin and the Chipmunks',
                     'Alvin and the Chipmunks: Chipwrecked',
                     'Alvin and the Chipmunks: The Road Chip',
                     'The Chipmunk Adventure',
                     'Prometheus',
                     'Aliens',
                     'Alien Vs. Predator',
                     'Alien',
                     'Alien: Covenant',
                     'Alien 3',
                     'Alien Resurrection',
                     'Aliens Vs. Predator - Requiem',
                     'Alice in Wonderland (2010)',
                     'Alice Through the Looking Glass',
                     'Along Came a Spider',
                     'Kiss the Girls',
                     'Alex Cross',
                     'Dumb and Dumber',
                     'Dumb and Dumber To',
                     'Dumb and Dumberer: When Harry Met Lloyd',
                     'Dolphin Tale',
                     'Dolphin Tale 2',
                     'Beauty and the Beast (2017)',
                     'The Jungle Book (2016)',
                     'Alice in Wonderland (2010)',
                     'Maleficent',
                     'Oz The Great and Powerful',
                     'Cinderella (2015)',
                     'Alice Through the Looking Glass',
                     'Sudden Impact',
                     'The Enforcer',
                     'Magnum Force',
                     'The Dead Pool',
                     'Live Free or Die Hard',
                     'Die Hard 2: Die Harder',
                     'Die Hard: With A Vengeance',
                     'Die Hard',
                     'A Good Day to Die Hard',
                     'Diary of a Wimpy Kid',
                     'Diary of a Wimpy Kid: Rodrick Rules',
                     'Diary of a Wimpy Kid: Dog Days',
                     'Diary of a Wimpy Kid: The Long Haul',
                     'Rambo: First Blood Part II',
                     'Rambo III',
                     'First Blood',
                     'Rambo',
                     'The Raid: Redemption',
                     'The Raid 2',
                     'The Purge: Election Year',
                     'The Purge: Anarchy',
                     'The Purge',
                     'Psycho II',
                     'Psycho',
                     'Psycho (1998)',
                     'Psycho III',
                     'Alien Vs. Predator',
                     'Predator',
                     'Predators',
                     'Aliens Vs. Predator - Requiem',
                     'Predator 2',
                     'Power Rangers (2017)',
                     "Mighty Morphin' Power Rangers",
                     'Turbo: A Power Rangers Movie',
                     "Porky's",
                     "Porky's II: The Next Day",
                     "Porky's Revenge (Part III)",
                     "Porky's (Re-issue)",
                     'Poltergeist',
                     'Poltergeist (2015)',
                     'Poltergeist II: The Other Side',
                     'Poltergeist III',
                     'Poltergeist (re-issue)',
                     'Police Academy',
                     'Police Academy 2: Their First Assignment',
                     'Police Academy 3: Back in Training',
                     'Police Academy 4: Citizens on Patrol',
                     'Police Academy 5: Assignment: Miami Beach',
                     'Police Academy 6: City Under Siege',
                     'Police Academy 7: Mission to Moscow',
                     'Pokemon: The First Movie',
                     'Pokemon: The Movie 2000',
                     'Pokemon 3: The Movie',
                     'Pokemon 4Ever',
                     'Pokemon Heroes',
                     'Ouija',
                     'Ouija: Origin of Evil',
                     'Ong Bak: The Thai Warrior',
                     'Ong Bak 2: The Beginning',
                     'Ong Bak 3',
                     'The Omen',
                     'The Omen (2006)',
                     "Ocean's Eleven",
                     "Ocean's Twelve",
                     "Ocean's Thirteen",
                     'Now You See Me',
                     'Now You See Me 2',
                     'Freddy Vs. Jason',
                     'A Nightmare on Elm Street (2010)',
                     'A Nightmare on Elm Street 4: The Dream Master',
                     'A Nightmare on Elm Street 3: Dream Warriors',
                     "Freddy's Dead: The Final Nightmare",
                     "A Nightmare on Elm Street 2: Freddy's Revenge",
                     'A Nightmare on Elm Street',
                     'A Nightmare on Elm Street 5: The Dream Child',
                     "Wes Craven's New Nightmare",
                     'Night at the Museum',
                     'Night at the Museum: Battle of the Smithsonian',
                     'Night at the Museum: Secret of the Tomb',
                     'The Neverending Story',
                     'The Neverending Story II',
                     'The Neverending Story III',
                     'Neighbors',
                     'Neighbors 2: Sorority Rising',
                     'The Naked Gun 2 1/2: The Smell of Fear',
                     'The Naked Gun: From the Files of Police Squad!',
                     'The Naked Gun 33 1/3: The Final Insult',
                     'The Muppets',
                     'The Muppet Movie',
                     'Muppets Most Wanted',
                     'Muppet Treasure Island',
                     'The Great Muppet Caper',
                     'The Muppet Christmas Carol',
                     'The Muppets Take Manhattan',
                     'Muppets from Space',
                     'The Mummy Returns',
                     'The Mummy',
                     'The Mummy: Tomb of the Dragon Emperor',
                     'The Scorpion King',
                     'Monsters University',
                     'Monsters, Inc.',
                     'Mission: Impossible II',
                     'Mission: Impossible - Ghost Protocol',
                     'Mission: Impossible - Rogue Nation',
                     'Mission: Impossible',
                     'Mission: Impossible III',
                     'The Girl with the Dragon Tattoo',
                     'The Girl Who Played with Fire',
                     "The Girl Who Kicked the Hornet's Nest",
                     'The Mighty Ducks',
                     'D2: The Mighty Ducks',
                     'D3: The Mighty Ducks',
                     'The Lord of the Rings: The Return of the King',
                     'The Lord of the Rings: The Two Towers',
                     'The Lord of the Rings: The Fellowship of the Ring',
                     'The Hobbit: An Unexpected Journey',
                     'The Hobbit: The Desolation of Smaug',
                     'The Hobbit: The Battle of the Five Armies',
                     'Men in Black',
                     'Men in Black II',
                     'MIB 3',
                     'Mechanic: Resurrection',
                     'The Giant Mechanical Man',
                     'Lethal Weapon 2',
                     'Lethal Weapon 3',
                     'Lethal Weapon 4',
                     'Lethal Weapon',
                     'The LEGO Movie',
                     'The LEGO Batman Movie',
                     'The LEGO Ninjago Movie',
                     'Kung Fu Panda',
                     'Kung Fu Panda 2',
                     'Kung Fu Panda 3',
                     'Kingsman: The Secret Service',
                     'Kingsman: The Golden Circle',
                     'King Kong',
                     'Kong: Skull Island',
                     'King Kong (1976)',
                     'King Kong Lives',
                     'King Kong (1933)',
                     'King Kong (Re-issues 1938, 1942, 1952)',
                     'Kick-Ass',
                     'Kick-Ass 2',
                     'The Karate Kid',
                     'The Karate Kid Part II',
                     'The Karate Kid',
                     'The Karate Kid Part III',
                     'The Next Karate Kid',
                     'Jurassic World',
                     'Jurassic Park',
                     'The Lost World: Jurassic Park',
                     'Jurassic Park III',
                     '22 Jump Street',
                     '21 Jump Street',
                     'Johnny English',
                     'Johnny English Reborn',
                     'Jeepers Creepers',
                     'Jeepers Creepers 2',
                     'Jeepers Creepers 3',
                     'Jaws',
                     'Jaws 2',
                     'Jaws 3-D',
                     'Jaws IV: The Revenge',
                     'Skyfall',
                     'Spectre',
                     'Quantum of Solace',
                     'Casino Royale',
                     'Die Another Day',
                     'The World Is Not Enough',
                     'Tomorrow Never Dies',
                     'GoldenEye',
                     'Moonraker',
                     'Octopussy',
                     'Thunderball',
                     'Never Say Never Again',
                     'For Your Eyes Only',
                     'The Living Daylights',
                     'Goldfinger',
                     'A View to a Kill',
                     'The Spy Who Loved Me',
                     'Diamonds Are Forever',
                     'You Only Live Twice',
                     'Live and Let Die',
                     'Licence to Kill',
                     'From Russia, with Love',
                     "On Her Majesty's Secret Service",
                     'The Man with the Golden Gun',
                     'Dr. No',
                     'Jackass 3-D',
                     'Jackass Presents: Bad Grandpa',
                     'Jackass: Number Two',
                     'Jackass: The Movie',
                     'Clear and Present Danger',
                     'The Hunt for Red October',
                     'The Sum of All Fears',
                     'Patriot Games',
                     'Jack Ryan: Shadow Recruit',
                     'Jack Reacher',
                     'Jack Reacher: Never Go Back',
                     'Harry Potter and the Deathly Hallows Part 2',
                     "Harry Potter and the Sorcerer's Stone",
                     'Harry Potter and the Half-Blood Prince',
                     'Harry Potter and the Deathly Hallows Part 1',
                     'Harry Potter and the Order of the Phoenix',
                     'Harry Potter and the Goblet of Fire',
                     'Harry Potter and the Chamber of Secrets',
                     'Harry Potter and the Prisoner of Azkaban',
                     'Fantastic Beasts and Where To Find Them',
                     'Harry Potter IMAX Marathon',
                     'It',
                     'Iron Man 3',
                     'Iron Man',
                     'Iron Man 2',
                     'Iron Eagle',
                     'Iron Eagle II',
                     'Aces: Iron Eagle III',
                     'Ip Man 3',
                     'Ip Man 2: Legend of the Grandmaster',
                     'Ip Man: The Final Fight',
                     'Insidious Chapter 2',
                     'Insidious',
                     'Insidious Chapter 3',
                     'Indiana Jones and the Kingdom of the Crystal Skull',
                     'Raiders of the Lost Ark',
                     'Indiana Jones and the Last Crusade',
                     'Indiana Jones and the Temple of Doom',
                     'Raiders of the Lost Ark (Re-issue) (1982)',
                     'Raiders of the Lost Ark (Re-issue) (1983)',
                     'Independence Day',
                     'Independence Day: Resurgence',
                     'An Inconvenient Truth',
                     'An Inconvenient Sequel: Truth to Power',
                     'Ice Age: Dawn of the Dinosaurs',
                     'Ice Age: The Meltdown',
                     'Ice Age',
                     'Ice Age: Continental Drift',
                     'Ice Age: Collision Course',
                     'The Hunger Games: Catching Fire',
                     'The Hunger Games',
                     'The Hunger Games: Mockingjay - Part 1',
                     'The Hunger Games: Mockingjay - Part 2',
                     'How to Train Your Dragon',
                     'How to Train Your Dragon 2',
                     'House Party',
                     'House Party 2',
                     'House Party 3',
                     'Hotel Transylvania 2',
                     'Hotel Transylvania',
                     'Hot Tub Time Machine',
                     'Hot Tub Time Machine 2',
                     'Home Alone',
                     'Home Alone 2: Lost in New York',
                     'Home Alone 3',
                     'The Hobbit: An Unexpected Journey',
                     'The Hobbit: The Desolation of Smaug',
                     'The Hobbit: The Battle of the Five Armies',
                     'Highlander 2: The Quickening',
                     'Highlander: Endgame',
                     'Highlander 3: The Final Dimension',
                     'Highlander',
                     'Herbie: Fully Loaded',
                     'The Love Bug',
                     'Hellraiser',
                     'Hellraiser III: Hell on Earth',
                     'Hellbound: Hellraiser II',
                     'Hellraiser 4: Bloodline',
                     'Clive Barker Presents: Hellraiser',
                     'A Haunted House',
                     'A Haunted House 2',
                     'Harry Potter and the Deathly Hallows Part 2',
                     "Harry Potter and the Sorcerer's Stone",
                     'Harry Potter and the Half-Blood Prince',
                     'Harry Potter and the Deathly Hallows Part 1',
                     'Harry Potter and the Order of the Phoenix',
                     'Harry Potter and the Goblet of Fire',
                     'Harry Potter and the Chamber of Secrets',
                     'Harry Potter and the Prisoner of Azkaban',
                     'Harry Potter IMAX Marathon',
                     'Harold and Kumar Escape from Guantanamo Bay',
                     'A Very Harold & Kumar 3D Christmas',
                     'Harold and Kumar Go to White Castle',
                     'Hannibal',
                     'The Silence of the Lambs',
                     'Red Dragon',
                     'Hannibal Rising',
                     'Manhunter',
                     'The Hangover',
                     'The Hangover Part II',
                     'The Hangover Part III',
                     'Halloween (2007)',
                     'Halloween: H20',
                     'Halloween',
                     'Halloween II (2009)',
                     'Halloween: Resurrection',
                     'Halloween II',
                     'Halloween 4: The Return of Michael Myers',
                     'Halloween: The Curse of Michael Myers',
                     'Halloween III: Season of the Witch',
                     'Halloween 5',
                     'Guardians of the Galaxy Vol. 2',
                     'Guardians of the Galaxy',
                     'Grown Ups',
                     'Grown Ups 2',
                     'Godzilla (2014)',
                     'Kong: Skull Island',
                     'Godzilla (2014)',
                     'Godzilla',
                     'Godzilla 2000',
                     'Godzilla 1985',
                     'Shin Godzilla',
                     'Godzilla (Original Japanese Version)',
                     'The Godfather',
                     'The Godfather Part III',
                     'The Godfather Part II',
                     'The Godfather (Re-issue)',
                     "God's Not Dead",
                     "God's Not Dead 2",
                     'Ghostbusters',
                     'Ghostbusters (2016)',
                     'Ghostbusters II',
                     'Ghostbusters (Re-issue)',
                     'Ghostbusters (30th Anniversary re-release)',
                     'Fright Night',
                     'Fright Night (2011)',
                     'Fright Night II',
                     'Freddy Vs. Jason',
                     'Friday the 13th (2009)',
                     'Friday the 13th (1980)',
                     'Friday the 13th Part III',
                     'Friday the 13th: Final Chapter',
                     'Friday the 13th - Part V',
                     'Friday the 13th Part 2',
                     'Friday the 13th Part VI',
                     'Friday the 13th Part VII',
                     'Jason Goes to Hell: The Final Friday',
                     'Friday the 13th Part VIII',
                     'Jason X',
                     'Next Friday',
                     'Friday After Next',
                     'Friday',
                     'Free Willy',
                     'Free Willy 2: The Adventure Home',
                     'Free Willy 3: The Rescue',
                     'Meet the Fockers',
                     'Meet the Parents',
                     'Little Fockers',
                     'Finding Dory',
                     'Finding Nemo',
                     'The Final Destination',
                     'Final Destination 3',
                     'Final Destination',
                     'Final Destination 2',
                     'Final Destination 5',
                     'Fifty Shades of Grey',
                     'Fifty Shades Darker',
                     'Furious 7',
                     'Fast & Furious 6',
                     'The Fate of the Furious',
                     'Fast Five',
                     'Fast and Furious',
                     'The Fast and the Furious',
                     '2 Fast 2 Furious',
                     'The Fast and the Furious: Tokyo Drift',
                     'Fantastic Four (2005)',
                     'Fantastic Four: Rise of the Silver Surfer',
                     'Fantastic Four',
                     'Fantastic Beasts and Where To Find Them',
                     'The Expendables',
                     'The Expendables 2',
                     'The Expendables 3',
                     'The Exorcist',
                     'Exorcist: The Beginning',
                     "The Exorcist Director's Cut",
                     'Exorcist II: The Heretic',
                     'The Exorcist III',
                     'Dominion: Prequel to the Exorcist',
                     'Evil Dead (2013)',
                     'Army of Darkness',
                     'Evil Dead 2',
                     'The Evil Dead',
                     'Evangelion: 3.0 You Can (Not) Redo',
                     'Evangelion 2.0: You Can (Not) Advance',
                     'Evangelion 1.0 You Are (Not) Alone',
                     'Ernest Saves Christmas',
                     'Ernest Goes to Jail',
                     'Ernest Goes to Camp',
                     'Ernest Scared Stupid',
                     'Ernest Rides Again',
                     'Once Upon a Time in Mexico',
                     'Desperado',
                     'El Mariachi',
                     'Earth (2009)',
                     'Dhoom 3',
                     'Dhoom 2',
                     'Dhoom',
                     'Despicable Me 2',
                     'Minions',
                     'Despicable Me 3',
                     'Despicable Me',
                     'Deadpool',
                     'Wonder Woman',
                     'Batman v Superman: Dawn of Justice',
                     'Suicide Squad',
                     'Man of Steel',
                     'The Mummy (2017)',
                     'The Dark Knight',
                     'The Dark Knight Rises',
                     'Batman Begins',
                     'The Dark Knight (2012 re-release)',
                     'Batman Begins (2012 re-release)',
                     'Crocodile Dundee',
                     'Crocodile Dundee II',
                     'Crocodile Dundee in Los Angeles',
                     'The Conjuring',
                     'The Conjuring 2',
                     'Annabelle: Creation',
                     'Annabelle',
                     'Conan the Barbarian',
                     'Conan the Destroyer',
                     'Conan the Barbarian (2011)',
                     'Cloverfield',
                     '10 Cloverfield Lane',
                     'Cloudy with a Chance of Meatballs',
                     'Cloudy with a Chance of Meatballs 2',
                     'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
                     'The Chronicles of Narnia: Prince Caspian',
                     'The Chronicles of Narnia: The Voyage of the Dawn Treader',
                     "Child's Play",
                     'Bride of Chucky',
                     "Child's Play 2",
                     'Seed of Chucky',
                     "Child's Play 3",
                     'Cars',
                     'Cars 2',
                     'Cars 3',
                     'The Care Bears Movie ',
                     'The Care Bears Movie 2',
                     'The Care Bears Movie 3',
                     'Captain America: Civil War',
                     'Captain America: The Winter Soldier',
                     'Captain America: The First Avenger',
                     "Bridget Jones's Diary",
                     'Bridget Jones: The Edge of Reason',
                     "Bridget Jones's Baby",
                     'The Bourne Ultimatum',
                     'The Bourne Supremacy',
                     'Jason Bourne',
                     'The Bourne Identity',
                     'The Bourne Legacy',
                     'The Blair Witch Project',
                     'Book of Shadows: Blair Witch 2',
                     'Blair Witch']
        for i,movie in enumerate(Movies_pg_list):
            first = '//table/tr[' + str(2*(i+1))
            second = str(2*(i+1))
            new_url = response.request.meta['url']
            if movie in Miss_list:
                yield scrapy.Request(
                    url='http://www.the-numbers.com' 
                        + (response.xpath('//tr['+str(2*(i+1)+']/td[3]/b/a/@href').extract())[:-7]+'cast-and-crew',        
                    callback =self.parse_dir,            #calls method below to extract data from each movie pg
                    meta={'url': new_url}
               )
     
        def parse_dir(self, response):
            url = response.request.meta['url']
                yield {
                      'url': url,
                      'Movie' : response.xpath(first+']/td/b/a/text()').extract(), 
                      'Director': response.xpath(first+']/td[@ class ="data"][2]/text()').extract(),
                      'Rel_Date': response.xpath(first+']/td/a/text()').extract(),
                      'Dom_Gross': response.xpath(first+']/td[@ class ="data"][3]/text()').extract(), 
                      'Wor_Gross': response.xpath(first+']/td[@ class ="data"][4]/text()').extract()    
                }
                  
                
                
                
                
                
             
        
        